# Generated by Django 2.0.4 on 2018-08-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_no', models.CharField(max_length=20)),
                ('department_made', models.CharField(max_length=20)),
                ('mission_name', models.CharField(max_length=100)),
                ('mission_background', models.CharField(max_length=300)),
                ('mission_dest', models.CharField(max_length=200)),
                ('group_category', models.CharField(max_length=20)),
                ('group_xinshi', models.CharField(max_length=20)),
                ('group_xiangmu', models.CharField(max_length=50)),
                ('group_xiangmu_category', models.CharField(max_length=20)),
                ('mission_country', models.CharField(max_length=15)),
                ('mission_past_country', models.CharField(max_length=20)),
                ('foreign_department', models.CharField(max_length=50)),
                ('mission_path', models.CharField(max_length=40)),
                ('group_peoples', models.IntegerField()),
                ('mission_start_time', models.DateField()),
                ('mission_end_time', models.DateField()),
                ('fee_source', models.CharField(max_length=40)),
                ('department_applied', models.CharField(max_length=30)),
                ('apply_operator', models.CharField(max_length=10)),
                ('group_operator', models.CharField(max_length=10)),
                ('group_operator_tel', models.CharField(max_length=15)),
                ('group_operator_fax', models.CharField(max_length=15)),
                ('group_operator_leader', models.CharField(max_length=10)),
                ('group_operator_leader_tel', models.CharField(max_length=15)),
                ('group_operator_leader_fax', models.CharField(max_length=15)),
                ('group_pijian_num', models.CharField(max_length=15)),
                ('group_pijian_date', models.DateField()),
                ('group_annotate', models.CharField(max_length=100)),
                ('group_state', models.CharField(max_length=20)),
                ('group_create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_num', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('pinyin', models.CharField(max_length=30)),
                ('sex', models.BooleanField()),
                ('birthday', models.DateField()),
                ('birth_province', models.CharField(max_length=15)),
                ('id_num', models.CharField(max_length=18)),
                ('company', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=10)),
                ('title_level', models.CharField(max_length=5)),
                ('post', models.CharField(max_length=15)),
                ('external_post', models.CharField(max_length=10)),
                ('post_level', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=10)),
                ('english_level', models.CharField(max_length=5)),
                ('job_attribute', models.CharField(max_length=10)),
                ('is_weiji', models.BooleanField()),
                ('is_report', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Outmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_type', models.CharField(max_length=10)),
                ('out_why', models.CharField(max_length=30)),
                ('out_time', models.DateTimeField()),
                ('out_opertor', models.CharField(max_length=10)),
                ('out_contactor', models.CharField(max_length=10)),
                ('out_contact_tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('auth_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('outin_state', models.CharField(max_length=10)),
                ('is_cancel', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('create_operator', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PassportOutIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outmenu_id', models.IntegerField()),
                ('in_time', models.DateTimeField()),
                ('in_operator', models.CharField(max_length=15)),
                ('passport_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guohechu.Passport')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='pass_port_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guohechu.Passport'),
        ),
    ]
