# Generated by Django 2.0.4 on 2018-08-21 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guohechu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='name',
            field=models.CharField(default='测试', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='pinyin',
            field=models.CharField(default='CESHI', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='apply_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_weiji',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outmenu',
            name='out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passport',
            name='auth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passport',
            name='create_operator',
            field=models.CharField(default='system', max_length=15),
        ),
        migrations.AlterField(
            model_name='passport',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passport',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passport',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passport',
            name='num',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passportoutin',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passportoutin',
            name='outmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guohechu.Outmenu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
