# Generated by Django 2.0.4 on 2018-08-22 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guohechu', '0003_passport_annotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
