# Generated by Django 2.0.4 on 2018-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guohechu', '0004_passport_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='sex',
            field=models.IntegerField(default=1),
        ),
    ]
