# Generated by Django 2.0.4 on 2018-08-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guohechu', '0005_passport_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='outmenu',
            name='is_all_back',
            field=models.BooleanField(default=False),
        ),
    ]
