# Generated by Django 2.0.4 on 2018-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guohechu', '0006_outmenu_is_all_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='outmenu',
            name='out_passports',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
